<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageVersionOverrideEnabled>false</CentralPackageVersionOverrideEnabled>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
    <DisableImplicitNuGetFallbackFolder>true</DisableImplicitNuGetFallbackFolder>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Kentico.Xperience.Admin" Version="31.5.3" />
    <PackageVersion Include="Kentico.Xperience.Azurestorage" Version="31.5.3" />
    <PackageVersion Include="Kentico.Xperience.Cloud" Version="31.5.3" />
    <PackageVersion Include="Kentico.Xperience.Imageprocessing" Version="31.5.3" />
    <PackageVersion Include="Kentico.Xperience.WebApp" Version="31.5.3" />
    <PackageVersion Include="SonarAnalyzer.CSharp" Version="10.27.0.140913" />
  </ItemGroup>
</Project>